### PR TITLE
Ticket #[69] modal

### PR DESCRIPTION
**Pull request by JonathonLLopez**
Passwords now have to match in order to complete submission. 
https://trello.com/c/lYAQqHFb/69-1-create-password-match-checker-for-signups

### CODE REVIEW

**Review by JonathanSBecker — CHANGES_REQUESTED** [review]
Line 24 shouldn't be a console log, it should also be inside of an else statement.

**Review by drewdistefano — COMMENTED** [review]
Looks good. These are the keys required by the signup route.

**Comment by drewdistefano** [comment]
agreed @JonathanSBecker, the client should let the user know the passwords don't match & should be inside an else statement

**Review by JonathanSBecker — APPROVED** [review]
Looks like it should work correctly now!

**Pull request merged**
