### PR TITLE
#17, Topic Page: Actions Container, https://trello.com/c/nWOelbLD/17-topic-page-actions-container

### PR DESCRIPTION
**Pull request by jayknyn**
Implemented the Actions Container that renders on the left side of the Topics Page. It displays 4 tiles for Volunteer, Donate, General Info and Charities.
Uses MaterialUI Card component

### CODE REVIEW

**Review by JonathanSBecker — CHANGES_REQUESTED** [review]
App.js conflicts

**Comment by ryanferrer** [comment]
Pull Request needs a ticket number and link to trello ticket in the description

**Review by ryanferrer — CHANGES_REQUESTED** [review]
Pull request requires associated ticket #

**Review by JonathanSBecker — APPROVED** [review]
All looks good.

**Review by ryanferrer — APPROVED** [review]

**Pull request merged**
